### ISSUE TITLE
Laravel scheduler: Cannot allocate memory

### ISSUE THREAD

**Issue by MrFallen** [HugoJF/csgo-sessions#4]
First error in logs.
`[2020-06-14 02:24:04] local.ERROR: proc_open(): fork failed - Cannot allocate memory {"exception":"[object] (ErrorException(code: 0): proc_open(): fork failed - Cannot allocate memory at /home/admin/web/csgo-sessions.play2earn.ru/vendor/symfony/console/Terminal.php:157)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'proc_open(): fo...', '/home/admin/web...', 157, Array)
#1 /home/admin/web/csgo-sessions.play2earn.ru/vendor/symfony/console/Terminal.php(157): proc_open('stty -a | grep ...', Array, NULL, NULL, NULL, Array)
#2 /home/admin/web/csgo-sessions.play2earn.ru/vendor/symfony/console/Terminal.php(143): Symfony\\Component\\Console\\Terminal::readFromProcess('stty -a | grep ...')
#3 /home/admin/web/csgo-sessions.play2earn.ru/vendor/symfony/console/Terminal.php(109): Symfony\\Component\\Console\\Terminal::getSttyColumns()
#4 /home/admin/web/csgo-sessions.play2earn.ru/vendor/symfony/console/Terminal.php(92): Symfony\\Component\\Console\\Terminal::initDimensionsUsingStty()
#5 /home/admin/web/csgo-sessions.play2earn.ru/vendor/symfony/console/Terminal.php(52): Symfony\\Component\\Console\\Terminal::initDimensions()
#6 /home/admin/web/csgo-sessions.play2earn.ru/vendor/symfony/console/Application.php(118): Symfony\\Component\\Console\\Terminal->getHeight()
#7 /home/admin/web/csgo-sessions.play2earn.ru/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#8 /home/admin/web/csgo-sessions.play2earn.ru/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 /home/admin/web/csgo-sessions.play2earn.ru/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#10 {main}
"} 
[2020-06-14 02:25:06] local.ERROR: proc_open(): fork failed - Cannot allocate memory {"exception":"[object] (ErrorException(code: 0): proc_open(): fork failed - Cannot allocate memory at /home/admin/web/csgo-sessions.play2earn.ru/vendor/symfony/process/Process.php:337)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'proc_open(): fo...', '/home/admin/web...', 337, Array)
#1 /home/admin/web/csgo-sessions.play2earn.ru/vendor/symfony/process/Process.php(337): proc_open(''/usr/bin/php7....', Array, Array, '/home/admin/web...', Array, Array)
#2 /home/admin/web/csgo-sessions.play2earn.ru/vendor/symfony/process/Process.php(234): Symfony\\Component\\Process\\Process->start(NULL, Array)
#3 /home/admin/web/csgo-sessions.play2earn.ru/vendor/laravel/framework/src/Illuminate/Console/Scheduling/Event.php(220): Symfony\\Component\\Process\\Process->run()
#4 /home/admin/web/csgo-sessions.play2earn.ru/vendor/laravel/framework/src/Illuminate/Console/Scheduling/Event.php(197): Illuminate\\Console\\Scheduling\\Event->runCommandInForeground(Object(Illuminate\\Foundation\\Application))
#5 /home/admin/web/csgo-sessions.play2earn.ru/vendor/laravel/framework/src/Illuminate/Console/Scheduling/ScheduleRunCommand.php(130): Illuminate\\Console\\Scheduling\\Event->run(Object(Illuminate\\Foundation\\Application))
#6 /home/admin/web/csgo-sessions.play2earn.ru/vendor/laravel/framework/src/Illuminate/Console/Scheduling/ScheduleRunCommand.php(90): Illuminate\\Console\\Scheduling\\ScheduleRunCommand->runEvent(Object(Illuminate\\Console\\Scheduling\\Event))
#7 [internal function]: Illuminate\\Console\\Scheduling\\ScheduleRunCommand->handle(Object(Illuminate\\Console\\Scheduling\\Schedule), Object(Illuminate\\Events\\Dispatcher))
#8 /home/admin/web/csgo-sessions.play2earn.ru/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#9 /home/admin/web/csgo-sessions.play2earn.ru/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /home/admin/web/csgo-sessions.play2earn.ru/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#11 /home/admin/web/csgo-sessions.play2earn.ru/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#12 /home/admin/web/csgo-sessions.play2earn.ru/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#13 /home/admin/web/csgo-sessions.play2earn.ru/vendor/laravel/framework/src/Illuminate/Console/Command.php(202): Illuminate\\Container\\Container->call(Array)
#14 /home/admin/web/csgo-sessions.play2earn.ru/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#15 /home/admin/web/csgo-sessions.play2earn.ru/vendor/laravel/framework/src/Illuminate/Console/Command.php(189): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#16 /home/admin/web/csgo-sessions.play2earn.ru/vendor/symfony/console/Application.php(1011): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /home/admin/web/csgo-sessions.play2earn.ru/vendor/symfony/console/Application.php(272): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Console\\Scheduling\\ScheduleRunCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /home/admin/web/csgo-sessions.play2earn.ru/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /home/admin/web/csgo-sessions.play2earn.ru/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /home/admin/web/csgo-sessions.play2earn.ru/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 /home/admin/web/csgo-sessions.play2earn.ru/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 {main}
"} 
[2020-06-14 02:26:04] local.ERROR: proc_open(): fork failed - Cannot allocate memory {"exception":"[object] (ErrorException(code: 0): proc_open(): fork failed - Cannot allocate memory at /home/admin/web/csgo-sessions.play2earn.ru/vendor/symfony/console/Terminal.php:157)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'proc_open(): fo...', '/home/admin/web...', 157, Array)
#1 /home/admin/web/csgo-sessions.play2earn.ru/vendor/symfony/console/Terminal.php(157): proc_open('stty -a | grep ...', Array, NULL, NULL, NULL, Array)
#2 /home/admin/web/csgo-sessions.play2earn.ru/vendor/symfony/console/Terminal.php(143): Symfony\\Component\\Console\\Terminal::readFromProcess('stty -a | grep ...')
#3 /home/admin/web/csgo-sessions.play2earn.ru/vendor/symfony/console/Terminal.php(109): Symfony\\Component\\Console\\Terminal::getSttyColumns()
#4 /home/admin/web/csgo-sessions.play2earn.ru/vendor/symfony/console/Terminal.php(92): Symfony\\Component\\Console\\Terminal::initDimensionsUsingStty()
#5 /home/admin/web/csgo-sessions.play2earn.ru/vendor/symfony/console/Terminal.php(52): Symfony\\Component\\Console\\Terminal::initDimensions()
#6 /home/admin/web/csgo-sessions.play2earn.ru/vendor/symfony/console/Application.php(118): Symfony\\Component\\Console\\Terminal->getHeight()
#7 /home/admin/web/csgo-sessions.play2earn.ru/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#8 /home/admin/web/csgo-sessions.play2earn.ru/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 /home/admin/web/csgo-sessions.play2earn.ru/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#10 {main}
"} 
[2020-06-14 02:27:04] local.ERROR: proc_open(): fork failed - Cannot allocate memory {"exception":"[object] (ErrorException(code: 0): proc_open(): fork failed - Cannot allocate memory at /home/admin/web/csgo-sessions.play2earn.ru/vendor/symfony/console/Terminal.php:157)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'proc_open(): fo...', '/home/admin/web...', 157, Array)
#1 /home/admin/web/csgo-sessions.play2earn.ru/vendor/symfony/console/Terminal.php(157): proc_open('stty -a | grep ...', Array, NULL, NULL, NULL, Array)
#2 /home/admin/web/csgo-sessions.play2earn.ru/vendor/symfony/console/Terminal.php(143): Symfony\\Component\\Console\\Terminal::readFromProcess('stty -a | grep ...')
#3 /home/admin/web/csgo-sessions.play2earn.ru/vendor/symfony/console/Terminal.php(109): Symfony\\Component\\Console\\Terminal::getSttyColumns()
#4 /home/admin/web/csgo-sessions.play2earn.ru/vendor/symfony/console/Terminal.php(92): Symfony\\Component\\Console\\Terminal::initDimensionsUsingStty()
#5 /home/admin/web/csgo-sessions.play2earn.ru/vendor/symfony/console/Terminal.php(52): Symfony\\Component\\Console\\Terminal::initDimensions()
#6 /home/admin/web/csgo-sessions.play2earn.ru/vendor/symfony/console/Application.php(118): Symfony\\Component\\Console\\Terminal->getHeight()
#7 /home/admin/web/csgo-sessions.play2earn.ru/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#8 /home/admin/web/csgo-sessions.play2earn.ru/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 /home/admin/web/csgo-sessions.play2earn.ru/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#10 {main}
"} 
[2020-06-14 02:29:03] local.ERROR: proc_open(): fork failed - Cannot allocate memory {"exception":"[object] (ErrorException(code: 0): proc_open(): fork failed - Cannot allocate memory at /home/admin/web/csgo-sessions.play2earn.ru/vendor/symfony/console/Terminal.php:157)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'proc_open(): fo...', '/home/admin/web...', 157, Array)
#1 /home/admin/web/csgo-sessions.play2earn.ru/vendor/symfony/console/Terminal.php(157): proc_open('stty -a | grep ...', Array, NULL, NULL, NULL, Array)
#2 /home/admin/web/csgo-sessions.play2earn.ru/vendor/symfony/console/Terminal.php(143): Symfony\\Component\\Console\\Terminal::readFromProcess('stty -a | grep ...')
#3 /home/admin/web/csgo-sessions.play2earn.ru/vendor/symfony/console/Terminal.php(109): Symfony\\Component\\Console\\Terminal::getSttyColumns()
#4 /home/admin/web/csgo-sessions.play2earn.ru/vendor/symfony/console/Terminal.php(92): Symfony\\Component\\Console\\Terminal::initDimensionsUsingStty()
#5 /home/admin/web/csgo-sessions.play2earn.ru/vendor/symfony/console/Terminal.php(33): Symfony\\Component\\Console\\Terminal::initDimensions()
#6 /home/admin/web/csgo-sessions.play2earn.ru/vendor/symfony/console/Application.php(119): Symfony\\Component\\Console\\Terminal->getWidth()
#7 /home/admin/web/csgo-sessions.play2earn.ru/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#8 /home/admin/web/csgo-sessions.play2earn.ru/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 /home/admin/web/csgo-sessions.play2earn.ru/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#10 {main}
"} 
[2020-06-14 02:30:10] local.INFO: Null event found {"rawEvent":false,"event":null} 
[2020-06-14 02:30:10] local.INFO: Processing took: 0.04 seconds to process 0 events [40.0 ms/event]  
[2020-06-14 02:30:11] local.INFO: Found 0 stale sessions {"sessions":{"Illuminate\\Support\\Collection":[]}} 
[2020-06-14 02:32:04] local.INFO: Null event found {"rawEvent":false,"event":null} 
[2020-06-14 02:32:04] local.INFO: Processing took: 0.04 seconds to process 0 events [40.0 ms/event]  
[2020-06-14 02:35:07] local.INFO: Null event found {"rawEvent":false,"event":null} 
[2020-06-14 02:35:07] local.INFO: Processing took: 0.03 seconds to process 0 events [30.0 ms/event]  `

Second error in random session.
https://flareapp.io/share/dmkonwm3

Can u help me? :(

**Comment by HugoJF** [comment]
How are you setting up your schedule?

I don't think this is related to `csgo-session` at all.

**Comment by MrFallen** [comment]
@HugoJF  And what could be the problem then? :( Is there little RAM on the server?
![image](https://user-images.githubusercontent.com/5339386/84590207-e2f0e200-ae77-11ea-9651-98ae259f00a6.png)

**Comment by HugoJF** [comment]
It seems like it's a RAM issue when Laravel is attempting to run the scheduler.

Since this is not related to `csgo-sessions`, I'll be closing this issue.

Feel free to open a new one if you find any new problems.
